version: '3.8'

services:
  site-doacoes:
    build:
      context: .
      dockerfile: Dockerfile.SiteDoacoes
    container_name: site-doacoes-container
    ports:
      - "80:3000"
    restart: unless-stopped